import {analyzeNeeds,recommendProducts,findPartialProducts} from './engine.mjs';
import {loadInventory} from './inventory.mjs';
const questions=[
 {key:'room',title:'AC ini untuk ruangan apa?',hint:'Pilih yang paling menggambarkan ruanganmu.',options:[['Kamar tidur','Kamar tidur'],['Ruang tamu','Ruang tamu'],['Ruang keluarga','Ruang keluarga'],['Ruang kerja','Ruang kerja'],['Kantor','Kantor'],['Toko/usaha','Toko / usaha'],['Lainnya','Lainnya']]},
 {key:'size',title:'Berapa ukuran ruangannya?',hint:'Cukup perkiraan panjang dan lebar ruangan dalam meter.',dimensions:true},
 {key:'ceiling',title:'Seberapa tinggi plafonnya?',hint:'Kalau tidak yakin, pilih tinggi plafon biasa.',options:[['low','Di bawah 2,5 meter'],['normal','2,5–3 meter'],['high','Di atas 3 meter']]},
 {key:'people',title:'Biasanya ada berapa orang?',hint:'Hitung orang yang sering berada di ruangan saat AC menyala.',options:[['1','1 orang'],['2','2 orang'],['3-4','3–4 orang'],['5+','5 orang atau lebih']]},
 {key:'sun',title:'Seberapa panas ruangan kamu?',hint:'Perhatikan paparan matahari, terutama siang dan sore.',options:[['none','Tidak terkena matahari langsung'],['little','Sedikit terkena matahari'],['moderate','Cukup terkena matahari'],['very','Sangat panas, terutama siang/sore']]},
 {key:'heat',title:'Banyak perangkat yang menghasilkan panas?',hint:'Misalnya TV, komputer, mesin, atau beberapa perangkat sekaligus.',options:[['none','Tidak ada'],['tv','TV / komputer'],['several','Beberapa perangkat elektronik'],['many','Banyak perangkat yang menghasilkan panas']]},
 {key:'hours',title:'AC akan menyala berapa lama per hari?',hint:'Tidak harus tepat, pilih yang paling mendekati kebiasaanmu.',options:[['<4','Kurang dari 4 jam'],['4-8','4–8 jam'],['8-12','8–12 jam'],['>12','Lebih dari 12 jam']]},
 {key:'priority',title:'Apa yang paling penting buat kamu?',hint:'Tidak ada jawaban benar atau salah.',options:[['harga','Harga lebih terjangkau'],['hemat','Hemat listrik'],['dingin','Cepat dingin'],['senyap','Lebih senyap'],['seimbang','Seimbang antara harga dan performa']]},
 {key:'inverter',title:'Mau AC inverter?',hint:'Kalau ragu, biarkan kami memilih berdasarkan kebutuhanmu.',options:[['yes','Ya, saya mau inverter'],['no','Tidak, saya pilih non-inverter'],['auto','Saya tidak tahu, pilihkan yang sesuai']]},
 {key:'budget',title:'Berapa budget untuk unit AC?',hint:'Budget khusus unit AC; biaya pemasangan bisa berbeda.',options:[['under3','Di bawah Rp3 juta'],['3-5','Rp3–5 juta'],['5-8','Rp5–8 juta'],['8-12','Rp8–12 juta'],['over12','Di atas Rp12 juta']]}
];
const state={step:0,answers:{},busy:false,advancing:false};let dimTimer=null;const $=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){clearTimeout(dimTimer);const q=questions[state.step];$('step-counter').textContent=`Pertanyaan ${state.step+1} dari ${questions.length}`;const pct=Math.round((state.step+1)/questions.length*100);$('progress-label').textContent=`${pct}%`;$('progress-fill').style.width=`${pct}%`;$('error').textContent='';$('back').disabled=state.step===0;$('next').disabled=state.busy;$('next').hidden=!q.dimensions;$('next').textContent=state.step===questions.length-1?'Lihat hasil ❄️':'Lanjut →';
 $('question').innerHTML=`<h2>${safe(q.title)}</h2><p class="hint">${safe(q.hint)}</p>`+(q.dimensions?`<div class="dimensions"><label>Panjang (meter)<input id="length" inputmode="decimal" type="number" min="1" max="30" step="0.1" placeholder="Contoh: 3" value="${safe(state.answers.length||'')}"></label><label>Lebar (meter)<input id="width" inputmode="decimal" type="number" min="1" max="30" step="0.1" placeholder="Contoh: 4" value="${safe(state.answers.width||'')}"></label></div><div class="measure" id="measure">Luas ruangan akan dihitung otomatis.</div>`:`<div class="options" role="group" aria-label="${safe(q.title)}">${q.options.map(([value,label])=>`<button type="button" class="option" data-value="${safe(value)}" aria-pressed="${state.answers[q.key]===value}">${safe(label)}</button>`).join('')}</div>`);
 if(q.dimensions){for(const id of ['length','width'])$(id).addEventListener('input',e=>{state.answers[id]=$(id).value;const a=Number(state.answers.length)*Number(state.answers.width);$('measure').textContent=a>0&&Number.isFinite(a)?`Perkiraan luas: ${Number(a.toFixed(1))} m²`:'Luas ruangan akan dihitung otomatis.';if(e.isTrusted)scheduleDimensionAdvance()});if(state.answers.length&&state.answers.width)$('length').dispatchEvent(new Event('input'))}
 else $('question').querySelectorAll('.option').forEach(btn=>btn.addEventListener('click',()=>{if(state.advancing)return;state.answers[q.key]=btn.dataset.value;$('question').querySelectorAll('.option').forEach(x=>x.setAttribute('aria-pressed',String(x===btn)));$('error').textContent='';state.advancing=true;setTimeout(()=>{state.advancing=false;advance()},180)}));
}
function advance(){const err=validate();if(err){$('error').textContent=err;return}if(state.step===questions.length-1)showResult();else{state.step++;render();document.querySelector('#wizard h2')?.focus?.()}}
function scheduleDimensionAdvance(){clearTimeout(dimTimer);dimTimer=setTimeout(()=>{const a=Number(state.answers.length),b=Number(state.answers.width);if(!(a>=1&&a<=30&&b>=1&&b<=30&&a*b<=250))return;$('measure').textContent=`Perkiraan luas: ${Number((a*b).toFixed(1))} m²`;advance()},700)}
function valueLabel(key,value){return questions.find(q=>q.key===key)?.options?.find(([v])=>v===value)?.[1]||value}
function validate(){const q=questions[state.step];if(q.dimensions){const a=Number(state.answers.length),b=Number(state.answers.width);if(!Number.isFinite(a)||!Number.isFinite(b)||a<1||b<1||a>30||b>30||a*b>250)return 'Isi panjang dan lebar antara 1–30 meter, dengan luas maksimal 250 m².'}else if(!state.answers[q.key])return 'Pilih satu jawaban untuk melanjutkan.';return ''}
function explain(need){const a=state.answers;const minutes={'<4':'kurang dari 4 jam','4-8':'4–8 jam','8-12':'8–12 jam','>12':'lebih dari 12 jam'};const sun={'none':'tidak terkena matahari langsung','little':'sedikit terkena matahari','moderate':'cukup terkena matahari','very':'sangat panas'};let why=need.manualType?`Kamu memilih tipe ${need.inverter?'inverter':'non-inverter'}, jadi kami menghormati pilihan itu.`:need.inverter?`Karena pemakaian ${minutes[a.hours]} per hari${a.priority==='hemat'?' dan kamu memprioritaskan efisiensi listrik':''}, inverter lebih sesuai untuk dipertimbangkan. Penghematan tetap bergantung pada suhu, kebiasaan, dan kondisi ruangan.`:`Untuk pola pemakaian ${minutes[a.hours]} per hari dan prioritas ${valueLabel('priority',a.priority).toLowerCase()}, non-inverter lebih masuk akal untuk dipertimbangkan. Ini bukan berarti inverter selalu lebih hemat.`;return `Ruangan ${safe(a.room).toLowerCase()} berukuran ${safe(a.length)} × ${safe(a.width)} meter, biasanya ditempati ${safe(valueLabel('people',a.people).toLowerCase())}, dan ${sun[a.sun]}. ${why} Berdasarkan ukuran, tinggi plafon, penghuni, paparan panas, serta perangkat elektronik, perkiraan kapasitasnya ${need.pk} PK. Ini panduan awal, bukan jaminan hasil untuk setiap kondisi bangunan.`}
function renderPartial(p){const price=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(p.price);return `<article class="product"><div><span class="badge">Perlu cek jenis AC</span><h3>${safe(p.brand)} ${safe(p.model||p.product_name)}</h3><p>${safe(p.pk)} PK · Jenis inverter belum diketahui · ${safe(price)} (harga acuan pemilik)</p><p>Ukuran dan budget tampak sesuai, tetapi tipe inverter/non-inverter belum dapat dipastikan. Pilih varian <strong>${safe(p.model||p.product_name)}</strong> dan periksa jenis serta harga terkini sebelum membeli.</p><a class="shopee" href="${safe(p.affiliate_url)}" target="_blank" rel="noopener noreferrer sponsored nofollow">🛒 Periksa di Shopee</a></div></article>`}
function renderProduct(item,need){const p=item.product;const price=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(p.price);const photo=p.image&&/^https:\/\//.test(p.image)?`<img src="${safe(p.image)}" alt="Foto ${safe(p.product_name)}" loading="lazy" referrerpolicy="no-referrer">`:'';const desc=`Kapasitas ${need.pk} PK sesuai estimasi ruangan, tipe ${need.inverter?'inverter':'non-inverter'} sesuai pilihan dan pola penggunaanmu.`;return `<article class="product">${photo}<div><span class="badge">${safe(item.label)}</span><h3>${safe(p.brand)} ${safe(p.model)}</h3><p>${safe(p.product_name)} · ${safe(p.pk)} PK · ${p.inverter?'Inverter':'Non-inverter'}</p><div class="price">${safe(price)} <small>(harga acuan)</small></div><p>${safe(desc)}</p><p>Harga dan varian diberikan pemilik; pilih varian <strong>${safe(p.model)}</strong> dan cek harga terkini di Shopee sebelum membeli.</p>${typeof p.rating==='number'?`<p>⭐ ${safe(p.rating)}${p.review_count!=null?` · ${safe(p.review_count)} ulasan`:''}</p>`:''}<a class="shopee" href="${safe(p.affiliate_url)}" target="_blank" rel="noopener noreferrer sponsored nofollow">🛒 Lihat di Shopee</a></div></article>`}
async function showResult(){if(state.busy)return;state.busy=true;$('next').disabled=true;$('error').textContent='';let need;try{need=analyzeNeeds(state.answers)}catch(e){$('error').textContent=e.message;state.busy=false;$('next').disabled=false;return}
 $('wizard').hidden=true;$('result').hidden=false;$('result').innerHTML='<div class="panel loading" role="status">Sedang memahami kebutuhan ruanganmu dan memeriksa katalog produk…</div>';await new Promise(resolve=>setTimeout(resolve,350));let rows=[],error=null;try{rows=await loadInventory()}catch(e){error=e.message}const matches=error?[]:recommendProducts(need,rows);const partial=error?[]:findPartialProducts(need,rows);const sum=[['Luas ruangan',`${Number(need.area.toFixed(1))} m²`],['Pengguna',valueLabel('people',need.people)],['Paparan panas',valueLabel('sun',need.sun)],['Pemakaian',`${valueLabel('hours',need.hours)}/hari`],['Tipe',need.inverter?'Inverter':'Non-inverter'],['Kapasitas',`${need.pk} PK`],['Budget',need.budget.label]];
 $('result').innerHTML=`<div class="result-intro"><div class="eyebrow">Hasil konsultasi kamu</div><h2>❄️ ${safe(need.pk===0.5?'½':need.pk===0.75?'¾':need.pk===1.5?'1½':need.pk)} PK ${need.inverter?'Inverter':'Non-inverter'}</h2><p>${explain(need)}</p></div><div class="panel"><h3>Kebutuhan kamu</h3><div class="summary">${sum.map(([k,v])=>`<div><small>${safe(k)}</small><strong>${safe(v)}</strong></div>`).join('')}</div>${need.overRange?'<p class="disclaimer">Ukuran dan beban panas melebihi kapasitas tunggal yang umum. Konsultasikan kemungkinan lebih dari satu unit sebelum membeli.</p>':''}<p class="disclaimer">Kapasitas ini perkiraan awal, bukan pengganti survei ruangan. Performa dan konsumsi listrik dipengaruhi kondisi bangunan, instalasi, dan cara pemakaian.</p><section class="products"><h2>Produk yang cocok</h2>${matches.length?matches.map(x=>renderProduct(x,need)).join(''):`<div class="empty"><strong>Belum ada produk terverifikasi yang pas dengan kebutuhan dan budget ini.</strong><p>${error?'Katalog belum dapat dimuat. Coba lagi nanti.':'Tautan produk sudah tercatat, tetapi kapasitas, tipe, dan harga belum dapat diverifikasi. Kami tidak akan menebak atau mengarahkanmu ke produk yang belum jelas.'}</p></div>`}</section>${partial.length?`<section class="products"><h2>Opsi yang perlu kamu periksa</h2><p class="hint">Data ukuran dan harga di bawah diberikan pemilik Aslan Teknik, tetapi tipe inverter belum diketahui. Ini bukan rekomendasi kecocokan penuh.</p>${partial.map(renderPartial).join('')}</section>`:''}<p class="disclosure">Beberapa tautan produk di halaman ini merupakan tautan afiliasi. Kami dapat menerima komisi jika kamu membeli melaluinya, tanpa biaya tambahan untuk kamu.</p><div class="bottom-cta"><h3>Masih ragu memilih?</h3><p>Kamu bisa meminta saran teknisi Aslan Teknik atau booking pemasangan.</p><a href="/booking">Booking layanan AC →</a></div><div class="controls"><button type="button" class="btn btn-back" id="restart">Mulai ulang</button></div></div>`;$('restart').addEventListener('click',()=>{state.step=0;state.answers={};state.busy=false;state.advancing=false;$('result').hidden=true;$('wizard').hidden=false;render();window.scrollTo({top:0,behavior:'smooth'})});state.busy=false;window.scrollTo({top:0,behavior:'smooth'});
}
$('back').addEventListener('click',()=>{if(state.step>0){state.step--;render()}});$('next').addEventListener('click',advance);render();
